media_entity_embeddable_video.settings:
  type: mapping
  label: 'Media entity embeddable video settings'
  mapping:
    local_images:
      type: string
      label: 'Base folder for tuhmbnails'
    grab_from:
      type: string
      label: 'From string used by Grab (sent with API requests)'
    grab_id:
      type: string
      label: 'ID to be used when building Grab embed code'
    aol_sid:
      type: string
      label: 'SID used by AOL (sent with API requests)'
    wochit_progn:
      type: string
      label: 'Publisher information used by Wochit ("progn" argument in embed code)'
    youtube:
      type: mapping
      label: 'YouTube'
      mapping:
        api_key:
          type: string
          label: 'API key'

media_entity.bundle.type.embeddable_video:
  type: mapping
  label: 'Embeddable video type configuration'
  mapping:
    source_field:
      type: string
      label: 'Field with embed code/URL'
